BunchofBrackets.MVCUI/Controllers/BracketController.cs
using BunchofBrackets.BL;
using BunchofBrackets.BL.Models;
using BunchofBrackets.MVCUI.Helper;
using BunchofBrackets.MVCUI.ViewModels;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Media;
using System.Web;
using System.Web.Mvc;

namespace BunchofBrackets.MVCUI.Controllers
{
    public class BracketController : Controller
    {
        // GET: Bracket
        public ActionResult Index()
        {
            return View(BracketManager.Load());
        }
        public ActionResult List(Guid id)
        {
            User user = UserManager.LoadById(id);
            List<Bracket> brackets = BracketManager.Load().Where(b => b.Moderator.Id == user.Id || Authenticate.IsParticipant(b, user)).ToList();
            return View(brackets);
        }
        public ActionResult Details(Guid id)
        {
            if (Authenticate.IsAuthenticated())
            {
                Bracket b = BracketManager.LoadById(id);
                BracketMatches bm = new BracketMatches(b, b.SortedMatches);
                bm.ViewingUser = (User)Session["user"];
                b.Matches.Where(m => m.Player2 == null).ForEach(m => m.Player2 = new BL.User());
                return View("Details", bm);
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }


        public ActionResult Create()
        {
            if (Authenticate.IsAuthenticated()) {
                Bracket bracket = new Bracket();
                User user = (User)Session["user"];
                
                user.Friends = RelationshipManager.LoadFriends(user);
                
                BracketFriends bracketFriends = new BracketFriends(user.Friends, bracket);

                return View(bracketFriends);
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        [HttpPost]
        public ActionResult Create(BracketFriends bracketFriends)
        {
            if (Authenticate.IsAuthenticated())
            {
                List<Guid> ids = bracketFriends.SelectedPlayerIds.ToList();


                Bracket bracket = bracketFriends.Bracket;
                if (bracketFriends.File != null)
                {
                    bracket.ImageSource = bracketFriends.File.FileName;
                    string target = Path.Combine(Server.MapPath("~/images"), Path.GetFileName(bracketFriends.File.FileName));

                    if (!System.IO.File.Exists(target))
                    {
                        bracketFriends.File.SaveAs(target);
                        ViewBag.Message = "File Uploaded Successfully";
                    }
                    else
                    {

                        ViewBag.Message = "File did not upload";
                    }
                }
                bracket.CurrentDivision = 1;
                bracket.Matches = Helper.ObjectManipulation.DivideIntoMatches(ids);

                bracket.Moderator = (User)Session["user"];
                bracket.OriginalRoundCount = bracket.Matches.Count;

                BracketManager.Insert(bracket);

                return RedirectToAction("Details", new {@id = bracket.Id });
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        public ActionResult Edit(Guid id)
        {
            if (Authenticate.IsAuthenticated())
            {
                return View(BracketManager.LoadById(id));
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        [HttpPost]
        public ActionResult Edit(Bracket bracket)
        {
            try
            {
                // TODO: Add update logic here
                BracketManager.Update(bracket);
                return RedirectToAction("Home");
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(bracket);
            }
        }
        public ActionResult Delete(Guid id)
        {
            if (Authenticate.IsAuthenticated())
            {
                return View(BracketManager.LoadById(id));
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        [HttpDelete]
        public ActionResult Delete(Bracket bracket)
        {
            try
            {
                // TODO: Add update logic here
                BracketManager.Delete(bracket.Id);
                return RedirectToAction("Home");
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(bracket);
            }
        }
    }
}

BunchofBrackets.MVCUI/Controllers/SearchController.cs
using BunchofBrackets.BL;
using BunchofBrackets.MVCUI.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BunchofBrackets.MVCUI.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index(SearchResults sr)
        {

            return View(sr);
        }

        public ActionResult Results(string searchterm)
        {
            SearchResults sr = new SearchResults();
            List<User> allUsers = UserManager.Load();
            List<Bracket> allBracket = BracketManager.Load();
            if (searchterm == null) searchterm = "";
            sr.SearchTerm = searchterm.ToLower();
            sr.Users = allUsers.Where(u => u.FullName.ToLower().Contains(searchterm) || u.Username.ToLower().Contains(searchterm));
            sr.Brackets = allBracket.Where(u => u.Name.ToLower().Contains(searchterm) || u.Game.ToLower().Contains(searchterm));
            if (sr.Users.Count() < 1 && sr.Brackets.Count() < 1) ViewBag.Message = "There are no results found with that query";
            return View(sr);
        }
    }
}

BunchofBrackets.MVCUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - BRACK IT</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/stylesheet.css" rel='stylesheet' />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>

    <script>
        var mini = true;

        function toggleSidenav() {
            if (mini) {
                console.log("opening sidenav");
                document.getElementById("mySidenav").style.width = "250px";
                document.getElementById("side").style.marginLeft = "250px";
                this.mini = false;
            } else {
                console.log("closing sidenav");
                document.getElementById("mySidenav").style.width = "85px";
                document.getElementById("side").style.marginLeft = "85px";
                this.mini = true;
            }
        }
    </script>

    <script>
    </script>
</head>
<body>

      <div class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
              <div class="navbar-header">
              </div>

              <!--<div class="flexboxx">
                  <div class="search">
                      <div>
                              <input type="text" placeholder="Search . . ." required>
                      </div>
                  </div>
              </div>-->

              <div class="profileImage" style="position: absolute; top: 15px; right: 0px;">
                  <a href="@Url.Action("Detail", null, new { id = Guid.Empty, area = string.Empty, controller = "User" }, Request.Url.Scheme)"><span><i class="material-icons" style="font-size:35px;">account_circle</i></span></a>
              </div>


              <div class="navbar-collapse collapse">
                  <ul class="nav navbar-nav">
                      <!--<li>@Html.ActionLink("Home", "Index", "Home")</li>
                  <li>@Html.ActionLink("Create Bracket", "Create", "Bracket")</li>
                  <li>@Html.ActionLink("Browse Brackets", "Index", "Bracket")</li>
                  <li>@Html.ActionLink("About", "About", "Home")</li>
                  <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                  <li><input type="text" placeholder="Search.." /></li>-->
                  </ul>
              </div>
          </div>
      </div> 

    <div id="side" style="font-family:'Abel', sans-serif;">
        <div id="mySidenav" class="sidenav" onmouseover="toggleSidenav()" onmouseout="toggleSidenav()">
            <a href="@Url.Action("Index", null, new { area = string.Empty, controller = "Home" }, Request.Url.Scheme)"><img class="logo" src="~/images/LogoB.png" /><span class="icon-text">HOME</span></a>

            <a href="@Url.Action("Detail", "User", new { @id = Guid.Empty})"><span><i class="material-icons">account_circle</i><span class="icon-text"></span>PROFILE</span></a><br>

            <a href="@Url.Action("Create", null, new { area = string.Empty, controller = "Bracket" }, Request.Url.Scheme)"><span><i class="material-icons">add_circle</i><span class="icon-text"></span>CREATE</span></a><br>

            <a href="@Url.Action("About", null, new { area = string.Empty, controller = "Home" }, Request.Url.Scheme)"><span><i class="material-icons">info</i><span class="icon-text"></span>ABOUT</span></a><br>

            <a href="@Url.Action("Contact", null, new { area = string.Empty, controller = "Home" }, Request.Url.Scheme)"><span><i class="material-icons">email</i><span class="icon-text"></span>CONTACT</span></a><br />
            <a href="@Url.Action("Index", "Search")"><span><i class="material-icons">search</i><span class="icon-text"></span>SEARCH</span></a>
        </div>
        <div>
            @RenderBody()
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>