BunchofBrackets.MVCUI/Controllers/BracketController.cs
using BunchofBrackets.BL;
using BunchofBrackets.BL.Models;
using BunchofBrackets.MVCUI.Helper;
using BunchofBrackets.MVCUI.ViewModels;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Media;
using System.Web;
using System.Web.Mvc;

namespace BunchofBrackets.MVCUI.Controllers
{
    public class BracketController : Controller
    {
        // GET: Bracket
        public ActionResult Index()
        {
            return View(BracketManager.Load());
        }
        public ActionResult List(Guid id)
        {
            User user = UserManager.LoadById(id);
            List<Bracket> brackets = BracketManager.Load().Where(b => b.Moderator.Id == user.Id || Authenticate.IsParticipant(b, user)).ToList();
            return View(brackets);
        }
        public ActionResult Details(Guid id)
        {
            if (Authenticate.IsAuthenticated())
            {
                Bracket b = BracketManager.LoadById(id);
                BracketMatches bm = new BracketMatches(b, b.SortedMatches);
                bm.ViewingUser = (User)Session["user"];
                b.Matches.Where(m => m.Player2 == null).ForEach(m => m.Player2 = new BL.User());
                return View("Details", bm);
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }


        public ActionResult Create()
        {
            if (Authenticate.IsAuthenticated()) {
                Bracket bracket = new Bracket();
                User user = (User)Session["user"];
                
                user.Friends = RelationshipManager.LoadFriends(user);
                
                BracketFriends bracketFriends = new BracketFriends(user.Friends, bracket);

                return View(bracketFriends);
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        [HttpPost]
        public ActionResult Create(BracketFriends bracketFriends)
        {
            if (Authenticate.IsAuthenticated())
            {
                List<Guid> ids = bracketFriends.SelectedPlayerIds.ToList();


                Bracket bracket = bracketFriends.Bracket;
                if (bracketFriends.File != null)
                {
                    bracket.ImageSource = bracketFriends.File.FileName;
                    string target = Path.Combine(Server.MapPath("~/images"), Path.GetFileName(bracketFriends.File.FileName));

                    if (!System.IO.File.Exists(target))
                    {
                        bracketFriends.File.SaveAs(target);
                        ViewBag.Message = "File Uploaded Successfully";
                    }
                    else
                    {

                        ViewBag.Message = "File did not upload";
                    }
                }
                bracket.CurrentDivision = 1;
                bracket.Matches = Helper.ObjectManipulation.DivideIntoMatches(ids);

                bracket.Moderator = (User)Session["user"];
                bracket.OriginalRoundCount = bracket.Matches.Count;

                BracketManager.Insert(bracket);

                return RedirectToAction("Details", new {@id = bracket.Id });
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        public ActionResult Edit(Guid id)
        {
            if (Authenticate.IsAuthenticated())
            {
                return View(BracketManager.LoadById(id));
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        [HttpPost]
        public ActionResult Edit(Bracket bracket)
        {
            try
            {
                // TODO: Add update logic here
                BracketManager.Update(bracket);
                return RedirectToAction("Home");
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(bracket);
            }
        }
        public ActionResult Delete(Guid id)
        {
            if (Authenticate.IsAuthenticated())
            {
                return View(BracketManager.LoadById(id));
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        [HttpDelete]
        public ActionResult Delete(Bracket bracket)
        {
            try
            {
                // TODO: Add update logic here
                BracketManager.Delete(bracket.Id);
                return RedirectToAction("Home");
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(bracket);
            }
        }
    }
}

BunchofBrackets.MVCUI/Controllers/MatchController.cs
using BunchofBrackets.BL;
using BunchofBrackets.BL.Models;
using BunchofBrackets.MVCUI.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BunchofBrackets.MVCUI.Controllers
{
    public class MatchController : Controller
    {
        // GET: Match
        public ActionResult Index()
        {
            return View();
        }

        // GET: Match/Details/5
        public PartialViewResult Details(Guid id)
        {
            return PartialView(id);
        }

        // GET: Match/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Match/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }




        // GET: Match/Edit/5
        public ActionResult Edit(Guid id)
        {
            var matchBracket = new MatchBracket(MatchManager.LoadById(id));

            if (Authenticate.IsParticipant(matchBracket.Match) || Authenticate.IsModerator(matchBracket.Bracket))
            {
                return View(matchBracket);
            }
            else
            {
                //TODO: Direct user to page that says they can't edit that match. possibly gray out matches that they are not part of 
                return RedirectToAction("Detail", "Bracket", new { returnurl = HttpContext.Request.Url });
            }
        }



        // POST: Match/Edit/5
        [HttpPost]
        public ActionResult Edit(MatchBracket matchBracket)
        {
            try
            {
                User user = (User)Session["user"];
                matchBracket.Match = MatchManager.LoadById(matchBracket.MatchId);
                matchBracket.Match.ReportingPlayer = user;
                matchBracket.Match.Winner = UserManager.LoadById(matchBracket.WinnerId);

                MatchManager.Update(matchBracket.Match);
                matchBracket.Bracket = BracketManager.LoadById(matchBracket.BracketId);

                if (matchBracket.Match.Winner != null)
                {
                    bool isDivisionOver = true;
                    for (int i = matchBracket.Bracket.GetFirstRoundOfDivision() - 1; i < matchBracket.Bracket.GetLastRoundOfDivision(); i++)
                    {
                        isDivisionOver = matchBracket.Bracket.SortedMatches[i].Winner != null;
                        //end the loop if any of the matches are not finished
                        if (isDivisionOver == false) break;
                    }

                    if (isDivisionOver)
                    {
                        for (int i = matchBracket.Bracket.GetFirstRoundOfDivision() - 1; i < matchBracket.Bracket.GetLastRoundOfDivision(); i += 2)
                        {
                            Match match = new Match();
                            match.Round = (int)Math.Ceiling((double)matchBracket.Bracket.SortedMatches[i].Round / 2) + matchBracket.Bracket.OriginalRoundCount;
                            if (i + 1 == matchBracket.Bracket.GetLastRoundOfDivision())
                            {
                                match.Player1 = matchBracket.Bracket.SortedMatches[i].Winner;
                                match.ReportingPlayer = match.Player1;
                                match.Winner = match.Player1;
                                match.Division = matchBracket.Bracket.CurrentDivision + 1;
                            }
                            else
                            {
                                match.Player1 = matchBracket.Bracket.SortedMatches[i].Winner;
                                match.Player2 = matchBracket.Bracket.SortedMatches[i + 1].Winner;
                                match.Division = matchBracket.Bracket.CurrentDivision + 1;
                            }
                            matchBracket.Bracket.Matches.Add(match);
                            MatchManager.Insert(match, matchBracket.Bracket.Id);
                        }
                        matchBracket.Bracket.CurrentDivision++;
                        BracketManager.Update(matchBracket.Bracket);
                    }
                }
                return RedirectToAction("Details", "Bracket", new { @id = matchBracket.BracketId });
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

        // GET: Match/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Match/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BunchofBrackets.MVCUI/Views/Bracket/Create.cshtml
@model BunchofBrackets.MVCUI.ViewModels.BracketFriends
@{
    ViewBag.Title = "Create";
}

<center style="margin-top:50px; margin-bottom:15px;"><img src="~/images/CreateBracket.png" /></center>


@using (Html.BeginForm("Create", "Bracket", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <center>
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <!--@Html.LabelFor(model => model.Bracket.Name, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-12">
                @Html.EditorFor(model => model.Bracket.Name, new { htmlAttributes = new { @class = "form-control", placeholder = "Bracket Name", style = "border-radius: 40px;" } })
                @Html.ValidationMessageFor(model => model.Bracket.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <!--@Html.LabelFor(model => model.Bracket.Game, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-12">
                @Html.EditorFor(model => model.Bracket.Game, new { htmlAttributes = new { @class = "form-control", placeholder = "Game Category", style = "border-radius: 40px;" } })
                @Html.ValidationMessageFor(model => model.Bracket.Game, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <!--@Html.LabelFor(model => model.Bracket.ImageSource, htmlAttributes: new { @class = "col-md-12"})-->
            <div class="col-md-12">
                <img src="~/Images/profile.png" class="imagepropmed" alt="@Model.Bracket.Name" id="bracketImage" style="border-radius: 10px; margin-top: 20px;" /><br /><br />
                <input type="file" name="File" id="File" accept="image/*" onchange="loadFile(event)" />
                @Html.ValidationMessageFor(model => model.Bracket.ImageSource, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedPlayerIds, htmlAttributes: new { @class = "col-md-12", style = "margin-top: 20px;" })
            <div class="col-md-12">
                @Html.DropDownListFor(model => model.SelectedPlayerIds, new SelectList(Model.Players, "Id", "FullName", Model.SelectedPlayerIds), null, new { @class = "form-control", @multiple = "multiple", size = 10 })
                @Html.ValidationMessageFor(model => model.SelectedPlayerIds, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Create" class="btn btn-default" style="border-radius: 40px; background-color: transparent; border-color: #6591ae; width: 100px; color: #6591ae;" />
            </div>
        </div>
    </div>
</center>
}


<script>
    var loadFile = function (event) {
        var output = document.getElementById('bracketImage');
        output.src = URL.createObjectURL(event.target.files[0])
    }
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BunchofBrackets.MVCUI/Views/Bracket/Details.cshtml
@model BunchofBrackets.MVCUI.ViewModels.BracketMatches

@{
    ViewBag.Title = "Details";
}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Holtwood+One+SC' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script|Herr+Von+Muellerhoff' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Istok+Web|Roboto+Condensed:700' rel='stylesheet' type='text/css'>
    <link href="~/Content/stylesheet.css" rel='stylesheet' />

</head>
<header class="hero">
    <div class="hero-wrap">
        <h1 id="headline">@Model.Bracket.Name</h1>
    </div>
</header>
@if (Model.Bracket.ImageSource == "profile.png")
{
    <img src="~/images/@Model.Bracket.ImageSource" class="imageprop" />
}

<br />
<div class="container">
    <div class="split split-one">

        @for (int i = 1; i <= Model.Bracket.FinalDivision; i++)
        {
            <div class="round round-one current">
                <div class="round-details">Round @i</div>

                @foreach (var match in Model.Matches.Where(m => m.Division == i))
                {
                    if ((Model.ViewingUser.Id == Model.Bracket.Moderator.Id || Model.ViewingUser.Id == match.Player1.Id || Model.ViewingUser.Id == match.Player2.Id) && match.Winner == null)
                    {

                        <a href="@Url.Action("Edit", "Match", new { @id = match.Id })" style="color: red">

                            <ul class="matchup">
                                <li class="team team-top">
                                    @match.Player1.FullName

                                </li>
                                <li class="team team-bottom">
                                    @match.Player2.FullName

                                </li>
                            </ul>
                        </a>
                    }
                    else
                    {
                        <ul class="matchup">

                            <li class="team team-top">
                                @match.Player1.FullName

                            </li>
                            <li class="team team-bottom">
                                @match.Player2.FullName

                            </li>
                        </ul>
                    }
                }
            </div>
        }

    </div>
</div>

BunchofBrackets.MVCUI/Views/Bracket/Index.cshtml
@model IEnumerable<BunchofBrackets.BL.Bracket>

@{
    ViewBag.Title = "Index";
}

<center style="margin-top:50px; margin-bottom:15px;"><img src="~/images/Browse.png" /></center>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Game)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CurrentDivision)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Name, "Details", new { id = item.Id })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Game)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CurrentDivision)
        </td>
    </tr>
}

</table>

BunchofBrackets.MVCUI/Views/Bracket/List.cshtml
@model IEnumerable<BunchofBrackets.BL.Bracket>

<div class="list">
    <h3 class="listtitle">Brackets</h3>
@foreach (var item in Model) {
    <div class="listitem">
        <div>
            @Html.ActionLink(item.Name, "Details", new { id = item.Id })
        </div>
    </div>
}

</div>