BunchofBrackets.MVCUI/Controllers/BracketController.cs
using BunchofBrackets.BL;
using BunchofBrackets.BL.Models;
using BunchofBrackets.MVCUI.Helper;
using BunchofBrackets.MVCUI.ViewModels;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Media;
using System.Web;
using System.Web.Mvc;

namespace BunchofBrackets.MVCUI.Controllers
{
    public class BracketController : Controller
    {
        // GET: Bracket
        public ActionResult Index()
        {
            return View(BracketManager.Load());
        }
        public ActionResult List(Guid id)
        {
            User user = UserManager.LoadById(id);
            List<Bracket> brackets = BracketManager.Load().Where(b => b.Moderator.Id == user.Id || Authenticate.IsParticipant(b, user)).ToList();
            return View(brackets);
        }
        public ActionResult Details(Guid id)
        {
            if (Authenticate.IsAuthenticated())
            {
                Bracket b = BracketManager.LoadById(id);
                BracketMatches bm = new BracketMatches(b, b.SortedMatches);
                bm.ViewingUser = (User)Session["user"];
                b.Matches.Where(m => m.Player2 == null).ForEach(m => m.Player2 = new BL.User());
                return View("Details", bm);
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }


        public ActionResult Create()
        {
            if (Authenticate.IsAuthenticated()) {
                Bracket bracket = new Bracket();
                User user = (User)Session["user"];
                
                user.Friends = RelationshipManager.LoadFriends(user);
                
                BracketFriends bracketFriends = new BracketFriends(user.Friends, bracket);

                return View(bracketFriends);
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        [HttpPost]
        public ActionResult Create(BracketFriends bracketFriends)
        {
            if (Authenticate.IsAuthenticated())
            {
                List<Guid> ids = bracketFriends.SelectedPlayerIds.ToList();


                Bracket bracket = bracketFriends.Bracket;
                if (bracketFriends.File != null)
                {
                    bracket.ImageSource = bracketFriends.File.FileName;
                    string target = Path.Combine(Server.MapPath("~/images"), Path.GetFileName(bracketFriends.File.FileName));

                    if (!System.IO.File.Exists(target))
                    {
                        bracketFriends.File.SaveAs(target);
                        ViewBag.Message = "File Uploaded Successfully";
                    }
                    else
                    {

                        ViewBag.Message = "File did not upload";
                    }
                }
                bracket.CurrentDivision = 1;
                bracket.Matches = Helper.ObjectManipulation.DivideIntoMatches(ids);

                bracket.Moderator = (User)Session["user"];
                bracket.OriginalRoundCount = bracket.Matches.Count;

                BracketManager.Insert(bracket);

                return RedirectToAction("Details", new {@id = bracket.Id });
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        public ActionResult Edit(Guid id)
        {
            if (Authenticate.IsAuthenticated())
            {
                return View(BracketManager.LoadById(id));
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        [HttpPost]
        public ActionResult Edit(Bracket bracket)
        {
            try
            {
                // TODO: Add update logic here
                BracketManager.Update(bracket);
                return RedirectToAction("Home");
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(bracket);
            }
        }
        public ActionResult Delete(Guid id)
        {
            if (Authenticate.IsAuthenticated())
            {
                return View(BracketManager.LoadById(id));
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        [HttpDelete]
        public ActionResult Delete(Bracket bracket)
        {
            try
            {
                // TODO: Add update logic here
                BracketManager.Delete(bracket.Id);
                return RedirectToAction("Home");
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View(bracket);
            }
        }
    }
}

BunchofBrackets.MVCUI/Controllers/FriendController.cs
using BunchofBrackets.BL;
using BunchofBrackets.BL.Models;
using BunchofBrackets.MVCUI.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BunchofBrackets.MVCUI.Controllers
{
    public class FriendController : Controller
    {
        // GET: Friend
        public ActionResult FriendList()
        {
            if (Authenticate.IsAuthenticated())
            {
                return View(RelationshipManager.LoadFriends((User)Session["user"]));
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        public ActionResult AddFriend(User user)
        {
            if (Authenticate.IsAuthenticated())
            {
                User loggedinUser = (User)Session["user"];
                if (!RelationshipManager.isRelated(user, loggedinUser))
                {
                    Relationship relationship = new Relationship();
                    relationship.Friend1 = loggedinUser;
                    relationship.Friend2 = user;
                    relationship.isFriend = false;

                    RelationshipManager.Insert(relationship);

                    return View(user);
                }
                else
                {
                    ViewBag.Message = "You two are already friends";
                    return RedirectToAction("Detail", "User", new { id = user.Id });
                }
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        public ActionResult LoadRequests()
        {
            if (Authenticate.IsAuthenticated())
            {
                var requests = RelationshipManager.LoadUnapprovedReceived((User)Session["user"]);
                List<UsersRequest> ur = new List<UsersRequest>();
                foreach(var request in requests)
                {
                    ur.Add(new UsersRequest { Request = request, User = UserManager.LoadById(request.Friend1.Id) });
                }
                return View(ur);
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }

        }
        public ActionResult Confirm(Guid id)
        {
            if (Authenticate.IsAuthenticated())
            {
                Relationship relationship = RelationshipManager.LoadById(id);
                relationship.Friend2 = ((User)Session["user"]);
                relationship.isFriend = true;
                relationship.StartDate = DateTime.Now;
                RelationshipManager.Update(relationship);
                return View();
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
        public ActionResult Deny(Guid id)
        {
            if (Authenticate.IsAuthenticated())
            {
                RelationshipManager.Delete(id);
                return View();
            }
            else
            {
                return RedirectToAction("Login", "User", new { returnurl = HttpContext.Request.Url });
            }
        }
    }
}

BunchofBrackets.MVCUI/Views/User/Create.cshtml
@model BunchofBrackets.BL.User

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<head>
    <meta charset="utf-8" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script>
        $(document).ready(function () {
            $("#btnsubmit").prop("disabled", true);
            $("#Password").keyup(validate);
            $("#ConfirmationPassword").keyup(validate);
        });


        function validate() {
            var password1 = $("#Password").val();
            var password2 = $("#ConfirmationPassword").val();



            if (password1 == password2) {
                $("#btnsubmit").prop("disabled", false);
            }
            else {
                $("#btnsubmit").prop("disabled", true);
            }

        }

    </script>
</head>
<center style="margin-top:50px; margin-bottom:15px;"><img src="~/images/SignUp.png" /></center>


@using (Html.BeginForm("Create", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<center>
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <!--@Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-12">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "First name", style = "border-radius: 40px;" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <!--@Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-12">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Last name", style = "border-radius: 40px;" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <!--@Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-12">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", placeholder = "Username", style = "border-radius: 40px;" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <!--@Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-12">
                @Html.PasswordFor(model => model.Password, new { @class = "form-control", placeholder = "Password", style = "border-radius: 40px;" })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <!--@Html.LabelFor(model => model.ConfirmationPassword, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-12">
                @Html.PasswordFor(model => model.ConfirmationPassword, new { @class = "form-control", placeholder = "Confirm Password", style = "border-radius: 40px;" })
                @Html.ValidationMessageFor(model => model.ConfirmationPassword, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <!--@Html.LabelFor(model => model.ImageSource, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-12">
                <img src="~/Images/profile.png" class="imagepropmed" alt="@Model.Username" id="userImage" style="border-radius: 10px; margin-top: 20px;"/><br /><br />
                <input type="file" name="File" id="File" accept="image/*" onchange="loadFile(event)" style="border-radius:10px;" />
                @Html.ValidationMessageFor(model => model.ImageSource, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Register" class="btn btn-default" id="btnsubmit" style="border-radius:40px; background-color: transparent; border-color: #6591ae; width: 100px; color: #6591ae;" />
            </div>
        </div>
    </div>
</center>
}

<script>
    var loadFile = function (event) {
        var output = document.getElementById('userImage');
        output.src = URL.createObjectURL(event.target.files[0])
    }
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BunchofBrackets.MVCUI/Views/User/Detail.cshtml
@model BunchofBrackets.MVCUI.ViewModels.Profile

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<center style="margin-top:50px; margin-bottom:15px;"><img src="~/images/Profile1.png" /></center>
<center><h2>@Html.DisplayFor(model => model.ProfileUser.FullName)</h2></center>
<div class="col-md-3">
    <center>
        <img src="~/images/@Model.ProfileUser.ImageSource" class="detailImage" /> <br />
    </center>
</div>
<div class="col-md-3">
    <center>
        @if (Model.LoggedInUser.Id == Model.ProfileUser.Id)
        {
            <div class="friends">@{Html.RenderAction("FriendList", "Friend");}</div>
            <div class="friends">@{Html.RenderAction("LoadRequests", "Friend");}</div>

        }
        else
        {
            <button class="Button btnAddFriend"><span>@Html.ActionLink("+ Friend", "AddFriend", "Friend", Model.ProfileUser, null) </span></button>
        }
    </center>
</div>
<div class="col-md-3">
    <center>
        <div class="bracket">
            @{Html.RenderAction("List", "Bracket", new { @id = Model.ProfileUser.Id });}
        </div>
    </center>
</div>
<div class="col-md-12">
    <center>
        @if (Model.LoggedInUser.Id == Model.ProfileUser.Id)
        {
            <button class="Button "><span>@Html.ActionLink("Settings", "Edit", "User", new { @id = Model.LoggedInUser.Id }, null) </span></button>
            
            <button class="Button "><span>@Html.ActionLink("Logout", "Logout", "User")</span></button>
        }
    </center>
</div>

BunchofBrackets.MVCUI/Views/User/Edit.cshtml
@model BunchofBrackets.BL.User

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<center style="margin-top:50px; margin-bottom:15px;"><img src="~/images/Settings.png" /></center>


@using (Html.BeginForm("Edit", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<center>
    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)


        <div class="form-group">
            <!--@Html.LabelFor(model => model.ImageSource, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-12">
                <img src="~/Images/@Model.ImageSource" alt="@Model.Username" class="detailImage" /><br /><br />
                <input type="file" name="File" id="File" accept="image/*" onchange="loadFile(event)" style="border-radius: 10px; margin-top: 20px;" />
                @Html.ValidationMessageFor(model => model.ImageSource, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <!--@Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-12">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", placeholder = "First Name", style = "border-radius: 40px;" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <!--@Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-12">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", placeholder = "Last Name", style = "border-radius: 40px;" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <!--@Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-12">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", placeholder = "Username", style = "border-radius: 40px;" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Save" class="btn btn-default" style="border-radius:40px; background-color: transparent; border-color: #6591ae; width: 100px; color: #6591ae;" />
            </div>
        </div>
    </div>
</center>
}

<div>
    @Html.ActionLink("Back to Profile", "Detail", "User", new { Id = Guid.Empty },  null )
</div>
<script>
    var loadFile = function (event) {
        var output = document.getElementById('userImage');
        output.src = URL.createObjectURL(event.target.files[0])
    }
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BunchofBrackets.MVCUI/Views/User/Get.cshtml
@model IEnumerable<BunchofBrackets.BL.User>

@{
    ViewBag.Title = "Get";
}

<h2>Get</h2>

<table class="table">

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.ActionLink("View Profile", "Detail", new { id = item.Id }) 
        </td>
    </tr>
}

</table>

BunchofBrackets.MVCUI/Views/User/Login.cshtml
@model BunchofBrackets.BL.User

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    
<div class="form-horizontal">

    <center style="margin-top:50px; margin-bottom:15px;"><img src="~/images/Asset 11.png" /></center>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
<center>
    <div class="form-group" style="margin-top: 50px;">
        <!--@Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })-->
        <div class="col-md-12">
            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { placeholder = "Username", @class = "form-control", style = "border-radius: 40px;" } })
            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
        </div>
    </div>
</center>


    <center>
        <div class="form-group">
            <!--@Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })-->
            <div class="col-md-12">
                @Html.PasswordFor(model => model.Password, new { placeholder = "Password", @class = "form-control", style = "border-radius: 40px;" })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        </center>






        <center>
            <div class="form-group">
                <div class="col-md-12">
                    <input type="submit" value="Log in" class="btn btn-default" style="border-radius:40px; background-color: transparent; border-color: #6591ae; width: 100px; color: #6591ae;" />
                </div>
            </div>
        </center>
    </div>
    }

    <center>
        <div>
            @Html.ActionLink("Don't have an account? Create one!", "Create")
        </div>
    </center>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

BunchofBrackets.MVCUI/Views/User/Logout.cshtml
@{
    ViewBag.Title = "Logout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<br />
<h2>You are Loggedout</h2>